services:
  webserver:
    image: nginx-reverse:latest
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 7070:80
    depends_on:
      - app
    links:
      - app
  app:
    image: fastapi-devops:latest
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - database
    links:
      - database
  database:
    image: mysql:5.7
    env_file:
      - .dev.env
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
